import axios from "../axios.js"
import BaseParams from "../base_params.js"

class Params extends BaseParams {

  container_hash(){
    return {"recruitment":{"company_id":null,"age_limit":null,"title_id":null,"required_jlpt":null,"is_school_department_category_must":null,"is_consedering_japanese_level_growth":null,"is_available_by_mid_career":null,"is_available_from_overseas":null,"is_required_driver_license_before_join":null,"is_required_driver_license_after_join":null,"peculiar_apply_url":null,"is_released":null,"recruitment_detail":{"is_salary_decided_by_interview":null,"salary_min_for_professional_school_students":null,"salary_min_for_bachelor_students":null,"salary_min_for_master_students":null,"salary_max_for_professional_school_students":null,"salary_max_for_bachelor_students":null,"salary_max_for_master_students":null,"model_salary_allowance_value":null,"model_salary_allowance_value_description":{"ja":null,"en":null},"is_adopting_flextime":null,"work_start_at":null,"work_end_at":null,"work_break_time":null,"work_hours":null,"work_time_description":{"ja":null,"en":null},"selection_valued_point":{"ja":null,"en":null},"interview_dress_id":null,"has_training":null,"has_support_for_driver_license":null,"support_for_driver_license_description":{"ja":null,"en":null},"job_category_name_of_company":{"ja":null,"en":null},"job_description":{"ja":null,"en":null},"required_skills_description":{"ja":null,"en":null},"training_description":{"ja":null,"en":null},"allowances_description":{"ja":null,"en":null},"recruit_intl_students_reason_id":null,"issues_solved_by_intl_students_description":{"ja":null,"en":null}},"recruitment_required_language_levels":[{"language_id":null,"speaking_level_id":null,"listening_level_id":null,"writing_level_id":null,"reading_level_id":null}],"recruitment_required_language_examinations":[{"language_examination_id":null,"required_result":null}],"recruitment_company_offices":[{"company_office_id":null,"description":{"ja":null,"en":null}}],"recruitment_annually_data":[{"nendo_year":null,"num_of_hiring":null}],"recruitment_target_study_department_categories":[{"study_department_category_id":null}],"recruitment_required_personalities":[{"personality_id":null,"description":{"ja":null,"en":null}}],"recruitment_careers":[{"first_living_country_id":null,"last_living_country_id":null,"is_work_globaly":null,"years_in_first_country":null,"description":{"ja":null,"en":null}}],"recruitment_selections":[{"selection_type_id":null,"is_online":null,"place_id":null,"step_num":null,"recruitment_selection_languages":[{"language_id":null}]}],"recruitment_country_relations":[{"country_id":null}],"recruitment_required_skills":[{"skill_id":null,"description":{"ja":null,"en":null}}],"recruitment_job_categories":[{"job_category_id":null}],"recruitment_allowances":[{"allowance_id":null,"is_fixed":null,"value":null}],"recruitment_internal_datum":{"memo":null}}}
  }
}

export default {
  Params: Params,
  execute: function(params){
    return axios.patch("/jtj/commands/hf_member__register_recruitment", {params: params});
  }
}