import axios from "../axios.js"
import BaseParams from "../base_params.js"

class Params extends BaseParams {

  container_hash(){
    return {"user":{"email":null,"password":null,"phone_num":null,"home_country_id":null,"first_name":null,"last_name":null,"latest_school_department_category_id":null,"graduate_latest_school_at":null,"agree_policy_at":null,"password_confirmation":null,"page_language_id":null,"user_analytics_datum":{"first_campaign_name":null,"first_campaign_source":null,"first_campaign_term":null,"first_campaign_medium":null,"first_campaign_content":null,"first_campaign_cretaed_at":null,"sign_up_campaign_name":null,"sign_up_campaign_source":null,"sign_up_campaign_term":null,"sign_up_campaign_medium":null,"sign_up_campaign_content":null,"sign_up_campaign_cretaed_at":null},"user_language_skills":[{"id":null,"language_id":null,"speaking_level_id":null,"listening_level_id":null,"writing_level_id":null,"reading_level_id":null,"_destroy":null}],"user_universities":[{"id":null,"university_id":null,"university_academic_degree_id":null,"university_student_category_id":null,"study_department_category_id":null,"graduate_at":null,"enroll_at":null,"is_latest":null,"is_main_bachelor":null,"_destroy":null,"university":{"id":null,"local_name":null,"country_id":null,"english_name":null,"world_ranking":null,"is_created_by_user":null,"_destroy":null}}],"user_schools":[{"id":null,"school_category_id":null,"school_name":null,"country_id":null,"graduate_at":null,"enroll_at":null,"is_latest":null,"_destroy":null}]}}
  }

  defined_params(){
    return {"user":{"type":"Object","params":{"email":{"type":"String"},"password":{"type":"Method"},"phone_num":{"type":"String"},"home_country_id":{"type":"Integer"},"first_name":{"type":"String"},"last_name":{"type":"String"},"latest_school_department_category_id":{"type":"Integer"},"graduate_latest_school_at":{"type":"Date"},"agree_policy_at":{"type":"DateTime"},"password_confirmation":{"type":"Method"},"page_language_id":{"type":"Integer"},"user_analytics_datum":{"type":"Object","params":{"first_campaign_name":{"type":"String"},"first_campaign_source":{"type":"String"},"first_campaign_term":{"type":"String"},"first_campaign_medium":{"type":"String"},"first_campaign_content":{"type":"String"},"first_campaign_cretaed_at":{"type":"DateTime"},"sign_up_campaign_name":{"type":"String"},"sign_up_campaign_source":{"type":"String"},"sign_up_campaign_term":{"type":"String"},"sign_up_campaign_medium":{"type":"String"},"sign_up_campaign_content":{"type":"String"},"sign_up_campaign_cretaed_at":{"type":"DateTime"}}},"user_language_skills":{"type":"[Object]","params":{"id":{"type":"Integer"},"language_id":{"type":"Integer"},"speaking_level_id":{"type":"Integer"},"listening_level_id":{"type":"Integer"},"writing_level_id":{"type":"Integer"},"reading_level_id":{"type":"Integer"},"_destroy":{"type":"TrueClass"}}},"user_universities":{"type":"[Object]","params":{"id":{"type":"Integer"},"university_id":{"type":"Integer"},"university_academic_degree_id":{"type":"Integer"},"university_student_category_id":{"type":"Integer"},"study_department_category_id":{"type":"Integer"},"graduate_at":{"type":"Date"},"enroll_at":{"type":"Date"},"is_latest":{"type":"TrueClass"},"is_main_bachelor":{"type":"TrueClass"},"_destroy":{"type":"TrueClass"},"university":{"type":"Object","params":{"id":{"type":"Integer"},"local_name":{"type":"String"},"country_id":{"type":"Integer"},"english_name":{"type":"String"},"world_ranking":{"type":"Integer"},"is_created_by_user":{"type":"TrueClass"},"_destroy":{"type":"TrueClass"}}}}},"user_schools":{"type":"[Object]","params":{"id":{"type":"Integer"},"school_category_id":{"type":"Integer"},"school_name":{"type":"String"},"country_id":{"type":"Integer"},"graduate_at":{"type":"Date"},"enroll_at":{"type":"Date"},"is_latest":{"type":"TrueClass"},"_destroy":{"type":"TrueClass"}}}}}}
  }
}

export default {
  Params: Params,
  execute: function(params){
    return axios.patch("/jtj/commands/user__sign_up", {params: params});
  }
}